### ISSUE TITLE
heic图片压缩后旋转

### ISSUE THREAD

**Issue by fingdo** [forJrking/KLuban#15]
heic图片查看exif是有数据的，我看了源码的实现，是通过glide的一部分核心获取角度的，由于是heic，格式不同，所以取到的ImageType是UNKNOWN，所以角度获取到的是未知。但是glide显示却是正常的，KLuban直接拿了这个数据就有问题

**Comment by fingdo** [comment]
联系我的邮箱：fingdo@qq.com，我把图片发给你

**Comment by fingdo** [comment]
我已经修复了，看PR

**Comment by forJrking** [comment]
> 我已经修复了，看PR

谢谢你的support，之前删除ExifInterfaceImgHeaderParser 因为非JPEG图片出现压缩失败，因为ExifInterface获取属性时候抛出异常，我将会通过兼容这2个问题来修复一下。我会尽快发布新的版本

**Comment by fingdo** [comment]
可以加个QQ，可以一起讨论讨论问题  178357820
