### ISSUE TITLE
压缩后图片出现旋转问题

### ISSUE THREAD

**Issue by 1322202454** [forJrking/KLuban#5]
图片压缩前和压缩后出现90度旋转

**Comment by forJrking** [comment]
> 图片压缩前和压缩后出现90度旋转

建议把原图上传下，测试修复

**Comment by 1322202454** [comment]
我已经处理了是因为 图片压缩的时候  缩放和旋转一起使用的时候  图片没法旋转，我把这两个动作拆开  先缩放再旋转之后就可以了

**Comment by forJrking** [comment]
> 我已经处理了是因为 图片压缩的时候 缩放和旋转一起使用的时候 图片没法旋转，我把这两个动作拆开 先缩放再旋转之后就可以了

原因为postScale 不会清空 matrix，set方法会。修改此问题代码如下
```
        if (angle > 0) {
            matrix.postRotate(angle.toFloat())
        }
        //双线性压缩
        if (scale != 1f) {
            matrix.postScale(scale, scale)
        }
```
