### ISSUE TITLE
请问有非androidX的版本吗？

### ISSUE THREAD

**Issue by merhong2012** [forJrking/KLuban#6]
如题，因为在为公司写一个标准化的SDK，该SDK会对接多个APP平台，所以有些项目还未把androidX做迁移，所以是否可以提供一个非androidX的版本呢？

**Comment by forJrking** [comment]
kotlin 可以兼容java,编译后都是class,你可以直接使用的。不需要引入kotlin,只是api调用方式写法不同。另外 androidx 是主流，如果你不需要，可以自己更换最新android support库一样可以。或者使用luban作者原版本



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "merhong2012"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 下午3:40
收件人: "forJrking/KLuban"<KLuban@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [forJrking/KLuban] 请问有java非androidX的版本吗？ (#6)



如题，因为公司项目较老，还未把 kotlin和androidX做迁移，所以是否可以提供一个java且非androidX的版本呢？

**Comment by merhong2012** [comment]
> kotlin 可以兼容java,编译后都是class,你可以直接使用的。不需要引入kotlin,只是api调用方式写法不同。另外 androidx 是主流，如果你不需要，可以自己更换最新android support库一样可以。或者使用luban作者原版本
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "merhong2012"<notifications@github.com&gt;; 发送时间: 2021年1月12日(星期二) 下午3:40 收件人: "forJrking/KLuban"<KLuban@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [forJrking/KLuban] 请问有java非androidX的版本吗？ (#6) 如题，因为公司项目较老，还未把 kotlin和androidX做迁移，所以是否可以提供一个java且非androidX的版本呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，多谢。我自己替换一下。
