### ISSUE TITLE
建议在做工具类开源项目时尽量少引用其他库

### ISSUE THREAD

**Issue by amd110** [forJrking/KLuban#9]
引用你这个图片压缩顺带还把协程和LiveData引入了

**Comment by forJrking** [comment]
> 引用你这个图片压缩顺带还把协程和LiveData引入了

引入官方库的目的在于可以减少大量自己无用功，而且此项目目的在于研究和利用新技术带来便捷。并不是纯粹的工具库

**Comment by amd110** [comment]
> > 引用你这个图片压缩顺带还把协程和LiveData引入了
> 
> 引入官方库的目的在于可以减少大量自己无用功，而且此项目目的在于研究和利用新技术带来便捷。并不是纯粹的工具库

如果定位是这样确实没问题，如果定位是想给更多人使用我个人觉得就不妥了
